### ISSUE TITLE
MedGuiR v0.105 bug when attempting to search for update to Mednafen

### ISSUE THREAD

**Issue by 84L7H13R** [Speedvicio/MedGuiReborn#2] opened 2019-06-26 00:10 UTC
Clicking the blue arrow to search for an update to Mednafen opens a browser page to https://community.qualys.com/thread/16917-net-framework.  Dunno why because I already have the required .NET components, or at least I should.  Just did a clean reinstall of Windows and running the app again for the first time it said it had to download the files with Windows update (and it did because it doesn't complain about it anymore).  Anyway, I'm running Win 8.1 64bit.

**Comment by Speedvicio** [comment] 2019-06-26 21:00
Should be not a bug.
That page will be opened when MedGui detect that your OS doesn't have installed the Microsoft patch patch relative to TLS 1.2 support on .Net framework.
You should verify if your OS have already installed that patch, in your case should be this:
https://support.microsoft.com/it-it/help/3154520/support-for-tls-system-default-versions-included-in-the-net-framework

**Comment by 84L7H13R** [comment] 2019-06-29 01:04
Well, I don't see that in my installed updates nor in the current list of updates to be installed.  Odd that it would be required after having Windows update get the required things to run the gui in the first place.  Also odd that it only affects the Mednafen updater and not the MedGUI updater.  And why have the gui direct people to some obscure page in their browser like that anyway?  I find that to be very confusing for the end-user.  Sorry but I consider this a BUG.  If that update is required then it should have installed automatically with the other .NET stuff, or at least have a popup window letting people know "Sorry but you need this update from Windows to use the Mednafen updater option".  And I already have .NET 4.7, why is this using such an old version of .NET?

**Comment by Speedvicio** [comment] 2019-06-29 08:39
I I can understand your point of view as an end user, but the problems behind the code are a bit different.
The MedGuiR update will be performed in a different way respect Mednafen update.
The frontend get the MedGuiR update by a FTP request on a my personal server that not require a webrequest, Mednafen are hosted on github and in the past year github have implemented the Tls 1.2 protocol not supported by webrequest Net Framework 2.0 on win xp, vista, 7, 8.
Win xp is totally excluded from the direct update via the github page, defacto XP user can update Mednafen by my personal server.
Others user until windows 8 need to enable tls 1.2 protocol "on net framework 2.0/3.5"  by appling that patch or by changing any keys on windows registry, win 10 is not affected by this constraint, since the protocol is enabled by default.
This is a specific update relative to Net Framework ,it's a optional update.
About the use of a older Net framework , is the same reason that you use win 8 instead win 10, in the past medgui used net 3.5 (around 7 year ago), many users complain that the use of a net framework superior at 2.0 was not necessary, i have downgraded all code to make medguir compatible with all win os, I continued to use an old eeepc myself with win xp installed.
About the games order filter, MedGui do not use database to store the games list, it use a plain structured csv file, it do not perform query but you can order the game as they are, was more simple for me to make a list by taking a list from the folder without checking the type of game entered, the name on the type of console or other... satisfied ;).
Other answer about error log... don't pay attention to that, it was inserted just for my convenience in the debug phase.

To conclude, you can try this reg key https://forum.fobby.net/index.php?t=getfile&id=1096& to bypass the tls problem, i have do not test it on win 8 but seem that most win 7 user have sovled by appling it, anyway you can always restore your registry to original state by appling the "disable" key.

**Comment by Speedvicio** [comment] 2019-07-04 09:03
For Now I close this bug.
If you have others questions, reply or open another Issue.

**Closed by Speedvicio** 2019-07-04 09:03 UTC
